runtime: python39
entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 3
  target_throughput_utilization: 0.6

service: returnschedule

env_variables:
  OPENAI_KEY: "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"

runtime_config:
  python_version: 3